apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-website
  namespace: devsecops-lab
  labels:
    app: demo-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-website
  template:
    metadata:
      labels:
        app: demo-website
    spec:
      containers:
      - name: web
        image: devsecops-demo:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-website-svc
  namespace: devsecops-lab
spec:
  type: ClusterIP
  selector:
    app: demo-website
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-website-ingress
  namespace: devsecops-lab
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-website-svc
            port:
              number: 80
